"""asd

Revision ID: 0363f12e979d
Revises: 2536a9caae8d
Create Date: 2022-03-31 13:38:49.844923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0363f12e979d'
down_revision = '2536a9caae8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_error', sa.Column('last_update_info', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_error', 'last_update_info')
    # ### end Alembic commands ###
