"""Asfsgf

Revision ID: 2536a9caae8d
Revises: 3ce6382afdff
Create Date: 2022-03-30 20:04:13.930086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2536a9caae8d'
down_revision = '3ce6382afdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('error_after_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'error_after_minutes')
    # ### end Alembic commands ###
