"""asdasd

Revision ID: 27e7230c452c
Revises: 099cad911c17
Create Date: 2022-03-06 15:27:06.454043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e7230c452c'
down_revision = '099cad911c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Device', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Device', 'last_update')
    # ### end Alembic commands ###
