"""asdasd

Revision ID: 31c52868528a
Revises: 9e217f8bd787
Create Date: 2022-03-21 17:09:12.166119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c52868528a'
down_revision = '9e217f8bd787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_station_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_station_key', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pressure', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_station_data')
    # ### end Alembic commands ###
