"""fsdf

Revision ID: 3ce6382afdff
Revises: ec124ac969ff
Create Date: 2022-03-30 11:18:47.908573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ce6382afdff'
down_revision = 'ec124ac969ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=120), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('error_type', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_key')
    )
    op.drop_column('device', 'cash_box_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('cash_box_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('device_error')
    # ### end Alembic commands ###
