"""changes

Revision ID: 3d0af2a7b047
Revises: d96212572b97
Create Date: 2022-03-10 10:48:49.975172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d0af2a7b047'
down_revision = 'd96212572b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeviceSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=120), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('flow_hanac_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_max_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_proc_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('DeviceInfo', sa.Column('device_key', sa.String(length=120), nullable=False))
    op.drop_column('DeviceInfo', 'press_gorcakic_set')
    op.drop_column('DeviceInfo', 'device_id')
    op.drop_column('DeviceInfo', 'flow_proc_set')
    op.drop_column('DeviceInfo', 'flow_max_set')
    op.drop_column('DeviceInfo', 'k_gorcakic_set')
    op.drop_column('DeviceInfo', 'dp_gorcakic_set')
    op.drop_column('DeviceInfo', 'flow_hanac_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeviceInfo', sa.Column('flow_hanac_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('DeviceInfo', sa.Column('dp_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('DeviceInfo', sa.Column('k_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('DeviceInfo', sa.Column('flow_max_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('DeviceInfo', sa.Column('flow_proc_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('DeviceInfo', sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('DeviceInfo', sa.Column('press_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.drop_column('DeviceInfo', 'device_key')
    op.drop_table('DeviceSet')
    # ### end Alembic commands ###
