"""asdasdv

Revision ID: 4dcf3123ff05
Revises: 634aca47dd33
Create Date: 2022-03-22 17:22:41.790614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcf3123ff05'
down_revision = '634aca47dd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_box_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_box_user')
    # ### end Alembic commands ###
