""":asdasd

Revision ID: 50dd540e0a5b
Revises: 4dcf3123ff05
Create Date: 2022-03-22 18:39:01.981709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dd540e0a5b'
down_revision = '4dcf3123ff05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_data', sa.Column('cashier_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_data', 'cashier_id')
    # ### end Alembic commands ###
