"""asdsvdsfs

Revision ID: 634aca47dd33
Revises: 
Create Date: 2022-03-22 14:08:25.923165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634aca47dd33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=400), nullable=False),
    sa.Column('refresh_token', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cash_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('parent_key', sa.String(length=120), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('device_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=120), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('flow_auto', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_pastaci', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_drac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_past', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_sarqac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_hanac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('self_on_off', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_proc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_pastaci', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('today', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('monthly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=120), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('flow_hanac_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_max_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_proc_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('title')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_key', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pressure', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=18), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=15), nullable=True),
    sa.Column('last_name', sa.String(length=15), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('ticket', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('cash_box_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user')
    op.drop_table('station_data')
    op.drop_table('role_permission')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('device_station')
    op.drop_table('device_set')
    op.drop_table('device_info')
    op.drop_table('device')
    op.drop_table('client')
    op.drop_table('cash_box')
    op.drop_table('auth')
    # ### end Alembic commands ###
