"""sadsd

Revision ID: 6ab47979d5a0
Revises: 31c52868528a
Create Date: 2022-03-21 17:17:52.038865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab47979d5a0'
down_revision = '31c52868528a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_station_data', sa.Column('cash_box_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_station_data', 'cash_box_id')
    # ### end Alembic commands ###
