"""df

Revision ID: 6cbbe562d1ee
Revises: 979504c7175e
Create Date: 2022-04-13 12:18:37.574601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cbbe562d1ee'
down_revision = '979504c7175e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_set', 'flow_hanac_set')
    op.drop_column('device_set', 'press_gorcakic_set')
    op.drop_column('device_set', 'flow_auto_set')
    op.drop_column('device_set', 'k_gorcakic_set')
    op.drop_column('device_set', 'flow_proc_set')
    op.drop_column('device_set', 'flow_max_set')
    op.drop_column('device_set', 'onoff')
    op.drop_column('device_set', 'flow_auto_on_off')
    op.drop_column('device_set', 'master_flow_auto')
    op.drop_column('device_set', 'dp_gorcakic_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_set', sa.Column('dp_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('master_flow_auto', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('flow_auto_on_off', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('onoff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('device_set', sa.Column('flow_max_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('flow_proc_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('k_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('flow_auto_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('press_gorcakic_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('flow_hanac_set', mysql.DECIMAL(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###
