"""asdasda

Revision ID: 85a785ff33ea
Revises: b8f410efda6c
Create Date: 2022-03-17 18:03:25.472619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a785ff33ea'
down_revision = 'b8f410efda6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('firm', sa.Column('phone_number', sa.String(length=30), nullable=False))
    op.add_column('firm', sa.Column('email', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firm', 'email')
    op.drop_column('firm', 'phone_number')
    op.drop_table('cash_box')
    # ### end Alembic commands ###
