"""asdsfgd

Revision ID: 8a55cfc10929
Revises: 85a785ff33ea
Create Date: 2022-03-18 15:12:27.833043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a55cfc10929'
down_revision = '85a785ff33ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_box', 'firm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_box', sa.Column('firm_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
