"""fsdg

Revision ID: 979504c7175e
Revises: b35060a19a28
Create Date: 2022-04-12 18:18:59.523784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979504c7175e'
down_revision = 'b35060a19a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_set', sa.Column('flow_auto_set', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('onoff', sa.Boolean(), nullable=True))
    op.add_column('device_set', sa.Column('flow_auto_on_off', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('device_set', sa.Column('master_flow_auto', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_set', 'master_flow_auto')
    op.drop_column('device_set', 'flow_auto_on_off')
    op.drop_column('device_set', 'onoff')
    op.drop_column('device_set', 'flow_auto_set')
    # ### end Alembic commands ###
