"""asd

Revision ID: 9e217f8bd787
Revises: aae1ef18d98a
Create Date: 2022-03-21 13:42:48.027292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e217f8bd787'
down_revision = 'aae1ef18d98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_box', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('cash_box', sa.Column('description', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_box', 'description')
    op.drop_column('cash_box', 'name')
    # ### end Alembic commands ###
