"""Asdasd

Revision ID: a8a893203d81
Revises: a157b2f6fe6e
Create Date: 2022-03-05 15:55:00.370413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8a893203d81'
down_revision = 'a157b2f6fe6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'max_count_firms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('max_count_firms', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
