"""Asd

Revision ID: aae1ef18d98a
Revises: dc773f55cdc1
Create Date: 2022-03-21 13:21:24.153025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aae1ef18d98a'
down_revision = 'dc773f55cdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('firm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('activity_address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('device_station')
    # ### end Alembic commands ###
