"""asdas

Revision ID: ada55f64478c
Revises: 27e7230c452c
Create Date: 2022-03-07 09:14:48.391091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada55f64478c'
down_revision = '27e7230c452c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeviceInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('flow_auto', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_pastaci', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_drac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_past', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_sarqac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_hanac_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dp_gorcakic_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_max_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_proc_set', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_hanac', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('self_on_off', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_proc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_pastaci', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('press_gorcakic', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('today', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('monthly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DeviceInfo')
    # ### end Alembic commands ###
