"""fdsg

Revision ID: b35060a19a28
Revises: 0363f12e979d
Create Date: 2022-04-12 18:03:08.871967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35060a19a28'
down_revision = '0363f12e979d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_info', sa.Column('yesterday', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_info', 'yesterday')
    # ### end Alembic commands ###
