"""asda

Revision ID: b8f410efda6c
Revises: 3d0af2a7b047
Create Date: 2022-03-10 12:10:13.075501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f410efda6c'
down_revision = '3d0af2a7b047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Device', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Device', type_='unique')
    # ### end Alembic commands ###
