"""df1

Revision ID: cc22036d5769
Revises: 6cbbe562d1ee
Create Date: 2022-04-13 12:18:55.479056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc22036d5769'
down_revision = '6cbbe562d1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_set', sa.Column('flow_auto_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('flow_hanac_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('press_gorcakic_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('k_gorcakic_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('dp_gorcakic_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('flow_max_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('flow_proc_set', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('onoff', sa.Boolean(), nullable=True))
    op.add_column('device_set', sa.Column('flow_auto_on_off', sa.String(length=8), nullable=True))
    op.add_column('device_set', sa.Column('master_flow_auto', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_set', 'master_flow_auto')
    op.drop_column('device_set', 'flow_auto_on_off')
    op.drop_column('device_set', 'onoff')
    op.drop_column('device_set', 'flow_proc_set')
    op.drop_column('device_set', 'flow_max_set')
    op.drop_column('device_set', 'dp_gorcakic_set')
    op.drop_column('device_set', 'k_gorcakic_set')
    op.drop_column('device_set', 'press_gorcakic_set')
    op.drop_column('device_set', 'flow_hanac_set')
    op.drop_column('device_set', 'flow_auto_set')
    # ### end Alembic commands ###
