"""1s1s

Revision ID: d96212572b97
Revises: ada55f64478c
Create Date: 2022-03-07 11:17:57.647688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96212572b97'
down_revision = 'ada55f64478c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Device', sa.Column('parent_key', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Device', 'parent_key')
    # ### end Alembic commands ###
