"""df1121

Revision ID: e07157472367
Revises: b53534a68ad7
Create Date: 2022-04-13 12:20:26.375670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07157472367'
down_revision = 'b53534a68ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_set', sa.Column('flow_auto_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('flow_hanac_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('press_gorcakic_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('k_gorcakic_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('dp_gorcakic_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('flow_max_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('flow_proc_set', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('onoff', sa.Boolean(), nullable=True))
    op.add_column('device_set', sa.Column('flow_auto_on_off', sa.DECIMAL(precision=8, scale=5), nullable=True))
    op.add_column('device_set', sa.Column('master_flow_auto', sa.DECIMAL(precision=8, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_set', 'master_flow_auto')
    op.drop_column('device_set', 'flow_auto_on_off')
    op.drop_column('device_set', 'onoff')
    op.drop_column('device_set', 'flow_proc_set')
    op.drop_column('device_set', 'flow_max_set')
    op.drop_column('device_set', 'dp_gorcakic_set')
    op.drop_column('device_set', 'k_gorcakic_set')
    op.drop_column('device_set', 'press_gorcakic_set')
    op.drop_column('device_set', 'flow_hanac_set')
    op.drop_column('device_set', 'flow_auto_set')
    # ### end Alembic commands ###
